print("hi")
print("hello world")
print("my name is zuka")
print("im 14 years old")
print("i love my family")
print("i live in tbilisi")
print("i want to get good in programming")
print("my fav food is pizza")
print("i think georgian food is pretty tasty")
print("i got to school every day")
print("i love going to school and learning new things")
print("programming looks fun for now")
print("my cousin goes programming with me")
print("goa academy is pretty succesful")
print("im in 2 days a week course")
print("programming is not hard for now")
print("right now we are learning python")
print("while programming you have to be careful not to missspell")
print("on the first day we had to draw house")
print("drawing house was challenging because it was new for me")
print("this is my homework")